image: samueldebruyn/debian-git
pipelines:
  default:
    - step:
        deployment: production
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://31.170.166.114/public_html/