# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: samueldebruyn/debian-git

pipelines:
  custom: # Pipelines que podem ser chamadas manualmente
    deployment-to-staging: # Bloco do deploy para ambiente de homologação ( desenvolvimento - staging )
      - step:
         script:
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://31.170.166.114
  branches: # Pipelines que será executado no exáto momento que o Commit é feito no BitBuket
    staging:  
      - step:  
         script:  
          - echo "Aqui você pode habilitar tasks automaticas que serão executadas em cada commit feito."
